app = 'zendoai'
primary_region = 'syd'

[env]
PORT = "8080"

[services]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[experimental]
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1

[[vm]]
size = "shared-cpu-2x"
memory = "4gb"
cpu_kind = "shared"
cpus = 2
[build.args]
DOCKER_DEFAULT_PLATFORM = "linux/amd64"

[mounts]
source = "zendo_uploads"
destination = "/app/app/uploads"
