#!/usr/bin/env python3
"""
CLI to merge BLIP adapter models generated by BLIPit.py.

Two input modes are supported:
- LoRA adapter directory (contains adapter_config.json): merges LoRA into a base
  BLIP model and saves a standalone merged model.
- Full model directory (contains config.json and model weights): simply re-saves
  the model (or copies) to the output directory.

Processor/tokenizer are taken from the adapter directory if present, otherwise
from the base model.
"""

import argparse
import os
import shutil
import sys
from typing import Tuple


def _is_dir(p: str) -> bool:
    return isinstance(p, str) and os.path.isdir(p)


def _has_file(d: str, name: str) -> bool:
    return os.path.isfile(os.path.join(d, name))


def _detect_format(path: str) -> Tuple[bool, bool]:
    """
    Returns (is_peft_adapter, is_full_model)
    """
    if not _is_dir(path):
        return (False, False)
    is_peft = _has_file(path, "adapter_config.json")
    is_full = _has_file(path, "config.json") and (
        _has_file(path, "pytorch_model.bin") or _has_file(path, "model.safetensors")
    )
    return (is_peft, is_full)


def merge_lora(base_blip: str, adapter_dir: str, out_dir: str, dtype: str = "auto") -> None:
    try:
        from transformers import BlipForConditionalGeneration, BlipProcessor
    except Exception as e:
        raise RuntimeError("transformers is required to merge BLIP models") from e

    try:
        from peft import PeftModel
    except Exception as e:
        raise RuntimeError("peft is required to merge LoRA adapters") from e

    torch_dtype = None
    if dtype == "fp16":
        import torch
        torch_dtype = torch.float16
    elif dtype == "bf16":
        import torch
        torch_dtype = torch.bfloat16

    model = BlipForConditionalGeneration.from_pretrained(base_blip, torch_dtype=torch_dtype)
    peft_model = PeftModel.from_pretrained(model, adapter_dir)
    # Merge adapter weights into base and unload adapter hooks
    merged = peft_model.merge_and_unload()

    os.makedirs(out_dir, exist_ok=True)
    merged.save_pretrained(out_dir)

    # Prefer processor from adapter (BLIPit saves it); fallback to base
    try:
        proc = BlipProcessor.from_pretrained(adapter_dir)
    except Exception:
        proc = BlipProcessor.from_pretrained(base_blip)
    try:
        proc.save_pretrained(out_dir)
    except Exception:
        pass


def copy_or_resave_full_model(src_dir: str, out_dir: str) -> None:
    """If possible, do a fast copy. Fallback to load-and-save for consistency."""
    try:
        # Fast path: copy directory tree
        if os.path.abspath(src_dir) != os.path.abspath(out_dir):
            os.makedirs(out_dir, exist_ok=True)
            for name in os.listdir(src_dir):
                sp = os.path.join(src_dir, name)
                dp = os.path.join(out_dir, name)
                if os.path.isdir(sp):
                    # dirs_exist_ok is 3.8+
                    shutil.copytree(sp, dp, dirs_exist_ok=True)
                else:
                    shutil.copy2(sp, dp)
            return
    except Exception:
        # Fall back to load-and-save below
        pass

    try:
        from transformers import BlipForConditionalGeneration, BlipProcessor
        model = BlipForConditionalGeneration.from_pretrained(src_dir)
        proc = BlipProcessor.from_pretrained(src_dir)
        os.makedirs(out_dir, exist_ok=True)
        model.save_pretrained(out_dir)
        proc.save_pretrained(out_dir)
    except Exception as e:
        raise RuntimeError(f"Failed to copy or re-save model from {src_dir} -> {out_dir}: {e}")


def build_argparser():
    ap = argparse.ArgumentParser(description="Merge BLIP LoRA adapters (from BLIPit) into base model.")
    ap.add_argument("--adapter", required=True, help="Path to BLIPit output dir (adapter or full model).")
    ap.add_argument("--out", required=True, help="Output directory for merged full model.")
    ap.add_argument("--base-blip", default="Salesforce/blip-image-captioning-large",
                    help="Base BLIP model id or path for LoRA merge.")
    ap.add_argument("--dtype", choices=["auto", "fp16", "bf16"], default="auto",
                    help="Optional torch dtype to load base before merge.")
    ap.add_argument("--force", action="store_true", help="Overwrite output directory contents if exists.")
    return ap


def main():
    args = build_argparser().parse_args()

    adapter = args.adapter
    out_dir = args.out

    is_peft, is_full = _detect_format(adapter)
    if not (is_peft or is_full):
        print(f"Error: {adapter} does not appear to be a BLIP adapter or full model dir.", file=sys.stderr)
        print("- Expected adapter_config.json for LoRA or config.json + weights for full model.", file=sys.stderr)
        sys.exit(2)

    if os.path.exists(out_dir):
        if not args.force:
            print(f"Error: output directory exists: {out_dir} (use --force to overwrite)", file=sys.stderr)
            sys.exit(2)
    os.makedirs(out_dir, exist_ok=True)

    if is_peft:
        merge_lora(args.base_blip, adapter, out_dir, dtype=args.dtype)
        print(f"Merged LoRA adapter into base model -> {out_dir}")
    else:
        copy_or_resave_full_model(adapter, out_dir)
        print(f"Copied full BLIP model -> {out_dir}")


if __name__ == "__main__":
    main()
