name: Build Python Wheel and Push

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl unzip libssl-dev patchelf

      - name: Download and extract libtorch
        run: |
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.7.0%2Bcpu.zip -o libtorch.zip
          unzip libtorch.zip -d /opt
        env:
          LIBTORCH: /opt/libtorch
          LD_LIBRARY_PATH: /opt/libtorch/lib

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel with maturin
        working-directory: ./backend/rust
        run: |
          export LIBTORCH=/opt/libtorch
          export LD_LIBRARY_PATH=$LIBTORCH/lib
          maturin build --release --features python -o ./wheels --interpreter python3.12

      - name: Git LFS setup and push built wheel
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git lfs install
          git lfs track "*.whl"
          echo "*.whl filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
          git add .gitattributes backend/rust/wheels/*.whl
          git lfs uninstall
          git commit -m "Add built wheel with LFS" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
          git lfs install
