name: Build Python Wheel

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Print CWD
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl unzip libssl-dev patchelf

      - name: Download and extract libtorch
        run: |
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.7.0%2Bcpu.zip -o libtorch.zip
          unzip libtorch.zip -d /opt
        env:
          LIBTORCH: /opt/libtorch
          LD_LIBRARY_PATH: /opt/libtorch/lib

      - name: Install maturin
        run: pip install maturin

      - name: Create wheels directory
        run: mkdir -p /home/runner/work/zendo/zendo/backend/python/app/wheels

      - name: Build wheel with maturin
        working-directory: ./backend/rust
        run: |
          export LIBTORCH=/opt/libtorch
          export LD_LIBRARY_PATH=$LIBTORCH/lib
          maturin build --release --features python -o /home/runner/work/zendo/zendo/backend/python/app/wheels

      - name: Configure git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: List wheel directory contents
        working-directory: /home/runner/work/zendo/zendo/
        run: ls -la

      - name: Add wheel file to git
        run: |
          for wheel in ./backend/python/app/wheels/*.whl; do
            if [ -f "$wheel" ]; then
              git add "$wheel"
            fi
          done

      - name: Commit and push wheel
        run: |
          git lfs track "*.whl"
          git commit -m "Add built wheel from CI" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        continue-on-error: true
