name: Build Python Wheel

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Print CWD
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl unzip libssl-dev patchelf

      - name: Download and extract libtorch
        run: |
          curl -L https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.7.0%2Bcpu.zip -o libtorch.zip
          unzip libtorch.zip -d /opt
        env:
          LIBTORCH: /opt/libtorch
          LD_LIBRARY_PATH: /opt/libtorch/lib

      - name: Install maturin
        run: pip install maturin

      - name: Create wheels directory
        run: mkdir -p /home/runner/work/zendo/zendo/backend/python/app/wheels

      - name: Build wheel with maturin
        working-directory: ./backend/rust
        run: |
          export LIBTORCH=/opt/libtorch
          export LD_LIBRARY_PATH=$LIBTORCH/lib
          maturin build --release --features python -o /home/runner/work/zendo/zendo/backend/python/app/wheels

      - name: Configure git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: List wheel directory contents
        working-directory: /home/runner/work/zendo/zendo/
        run: ls -la

      - name: Push built wheel using Git LFS
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git lfs install
          git lfs track "*.whl"
          echo "*.whl filter=lfs diff=lfs merge=lfs -text" > .gitattributes
          git add .gitattributes

          git add backend/python/app/wheels/*.whl

          git commit -m "Add built wheel from CI" || echo "Nothing to commit"

          # Push using Personal Access Token
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
        continue-on-error: true
